// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgIK0h-5xltOjvPM_ItWC2BfvR_JQzpJc',
    appId: '1:70132718998:web:cdf6816c724a2284f611b7',
    messagingSenderId: '70132718998',
    projectId: 'unitpayoriginal',
    authDomain: 'unitpayoriginal.firebaseapp.com',
    storageBucket: 'unitpayoriginal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8G2uiuVrxTthA1HBYd2Xj_V_WPjJS_KM',
    appId: '1:70132718998:android:c883c10ba3551abbf611b7',
    messagingSenderId: '70132718998',
    projectId: 'unitpayoriginal',
    storageBucket: 'unitpayoriginal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRAbM-9vqv1ortfUU-Tzdz_AbSfHN9k1w',
    appId: '1:70132718998:ios:ab56dce53b1aa560f611b7',
    messagingSenderId: '70132718998',
    projectId: 'unitpayoriginal',
    storageBucket: 'unitpayoriginal.appspot.com',
    iosClientId: '70132718998-a02o7u4i81b4unvd0chivt84u89gsk12.apps.googleusercontent.com',
    iosBundleId: 'com.example.unitpay',
  );
}
